package components

var workingVerbs = []string{
	"Thinking…",
	"Working…",
	"Brrrrr…",
	"Shaking it crazy style...",
	"Not working just watching youtube...",
	"Posting conspiracy theories on reddit...",
	"Voting for your least favorite politician...",
	"Running rm -rf /*...",
	"Slacking your CEO...",
	"Texting your parents...",
	"Phoning a friend...",
	"Learning japanese...",
	"Checking StackOverflow...jk...imagine?...",
	"Reading The Stormlight Archive...",
	"Turning back time...",
	"Reticulating splines...",
	"Polishing the yak...",
	"Consulting the rubber duck...",
	"Convincing electrons to behave...",
	"Reheating yesterday's coffee...",
	"Asking the moon for permission...",
	"Downloading more RAM...",
	"Feeding crumbs to the compiler...",
	"Staring meaningfully at logs...",
	"Pretending the tests are fine...",
	"Negotiating with localhost...",
	"Herding goroutines...",
	"Untangling headphone cables...",
	"Reading tea leaves in stack traces...",
	"Applying artisanal duct tape...",
	"Summoning a senior engineer...",
	"Making the bits shinier...",
	"Checking if it's DNS...",
	"Checking if it's still DNS...",
	"Blaming cosmic rays...",
	"Watering the dependency tree...",
	"Teaching semicolons manners...",
	"Looking busy for management...",
	"Sharpening tiny pencils...",
	"Turning bugs off and on again...",
	"Filing paperwork with the void...",
	"Asking Clippy for emotional support...",
	"Measuring twice, deleting once...",
	"Consulting ancient commit messages...",
	"Vacuuming the token cache...",
	"Warming up the lasers...",
	"Defragmenting vibes...",
	"Counting parentheses by candlelight...",
	"Chasing a raccoon out of the build...",
	"Installing left-pad spiritually...",
	"Reading Hacker News responsibly...",
	"Ignoring Hacker News responsibly...",
	"Teaching regex about boundaries...",
	"Brewing a segmentation fault...",
	"Rebalancing the vibes tree...",
	"Asking git nicely...",
	"Looking for the any key...",
	"Patching the space-time continuum...",
	"Consulting the changelog oracle...",
	"Taming a feral JSON blob...",
	"Folding fitted sheets in YAML...",
	"Optimizing for cozy...",
	"Letting the smoke out gently...",
	"Putting the smoke back in...",
	"Auditioning new loading excuses...",
	"Doing crimes against whitespace...",
	"Reading documentation backwards...",
	"Inventing a new edge case...",
	"Bribing the scheduler...",
	"Asking SQLite to share...",
	"Listening to the modem sing...",
	"Painting racing stripes on the CLI...",
	"Making terminal noises quietly...",
	"Searching under the couch cushions...",
	"Teaching tabs and spaces diplomacy...",
	"Reassuring the heap...",
	"Giving the stack a pep talk...",
	"Translating from developer to computer...",
	"Translating from computer to regret...",
	"Finding a smaller hammer...",
	"Wiggling the cables...",
	"Checking whether mercury is in retrograde...",
	"Combing through yak fur...",
	"Rendering unto Caesar's cipher...",
	"Putting pants on the AST...",
	"Flossing the message bus...",
	"Running a tiny committee meeting...",
	"Asking the linter to be cool...",
	"Teaching the cache object permanence...",
	"Looking for snacks in /tmp...",
	"Rebuilding confidence from source...",
	"Staring at a blinking cursor...",
	"Counting tokens on fingers...",
	"Counting tokens on toes...",
	"Preparing a strongly worded TODO...",
	"Negotiating with the permission modal...",
	"Making sure nobody imported cmd/...",
	"Dusting the sidebar...",
	"Greasing the scroll wheel...",
	"Inflating the context window...",
	"Taking the scenic code path...",
	"Asking the provider if it's awake...",
	"Waiting for the cloud to remember...",
	"Practicing responsible autocomplete...",
	"Reading your mind, poorly...",
	"Replaying the incident in slow motion...",
	"Finding the load-bearing comment...",
	"Replacing magic with slightly better magic...",
	"Making a tiny diff enormous emotionally...",
	"Stabilizing the quantum spinner...",
	"Explaining recursion to itself...",
	"Convincing nil to stay home...",
	"Writing a haiku about latency...",
	"Letting the goroutines stretch...",
	"Asking the MCP servers how they feel...",
	"Taking attendance in the tool registry...",
	"Opening a portal to localhost...",
	"Refactoring the vibes, not the code...",
	"Making sure the chimney still smokes...",
	"Searching for a humane truncation...",
	"Teaching the viewport to share...",
	"Rolling for initiative...",
	"Checking the blast radius...",
	"Hiding complexity under a nice border...",
	"Giving the spinner a side quest...",
	"Making eye contact with the race detector...",
	"Waiting for entropy to settle...",
	"Filing a bug with reality...",
	"Asking the terminal for consent...",
	"Re-indexing the vibes database...",
	"Pretending this was the plan...",
	"Making one weird trick work locally...",
	"Clearing throat in binary...",
	"Compressing suspense...",
	"Poking the daemon with a stick...",
	"Trying not to wake the flakes...",
	"Checking if the answer is 42...",
	"Consulting the tiny council of structs...",
	"Folding errors into context...",
	"Sharpening the axe before deleting...",
	"Putting the cozy in code...",
}

// RandomWorkingVerb selects one busy footer label. Callers should store the
// returned value and rotate it deliberately so spinner ticks do not change the
// label every frame.
func RandomWorkingVerb() string {
	return randomPlaceholder(workingVerbs)
}
