//go:build ignore

// gen_iterm_themes imports Windows Terminal JSON themes from
// mbadolato/iTerm2-Color-Schemes and emits iterm_themes_generated.go.
package main

import (
	"archive/tar"
	"compress/gzip"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const sourceURL = "https://github.com/mbadolato/iTerm2-Color-Schemes/releases/latest/download/windowsterminal-themes.tgz"

type wtScheme struct {
	Name                string `json:"name"`
	Black               string `json:"black"`
	Red                 string `json:"red"`
	Green               string `json:"green"`
	Yellow              string `json:"yellow"`
	Blue                string `json:"blue"`
	Purple              string `json:"purple"`
	Cyan                string `json:"cyan"`
	White               string `json:"white"`
	BrightBlack         string `json:"brightBlack"`
	BrightRed           string `json:"brightRed"`
	BrightGreen         string `json:"brightGreen"`
	BrightYellow        string `json:"brightYellow"`
	BrightBlue          string `json:"brightBlue"`
	BrightPurple        string `json:"brightPurple"`
	BrightCyan          string `json:"brightCyan"`
	BrightWhite         string `json:"brightWhite"`
	Background          string `json:"background"`
	Foreground          string `json:"foreground"`
	CursorColor         string `json:"cursorColor"`
	SelectionBackground string `json:"selectionBackground"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	resp, err := http.Get(sourceURL) //nolint:gosec // generator-only updater for public theme archive
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("download %s: %s", sourceURL, resp.Status)
	}
	gz, err := gzip.NewReader(resp.Body)
	if err != nil {
		return err
	}
	defer gz.Close()
	tr := tar.NewReader(gz)
	var schemes []wtScheme
	for {
		h, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return err
		}
		if h.FileInfo().IsDir() || filepath.Ext(h.Name) != ".json" {
			continue
		}
		var s wtScheme
		if err := json.NewDecoder(tr).Decode(&s); err != nil {
			return fmt.Errorf("decode %s: %w", h.Name, err)
		}
		if s.Name == "" {
			s.Name = strings.TrimSuffix(filepath.Base(h.Name), ".json")
		}
		schemes = append(schemes, s)
	}
	sort.Slice(schemes, func(i, j int) bool { return themeSlug(schemes[i].Name) < themeSlug(schemes[j].Name) })
	return os.WriteFile("iterm_themes_generated.go", []byte(render(schemes)), 0o644)
}

func uniqueSlugs(schemes []wtScheme) []string {
	seen := map[string]int{}
	slugs := make([]string, len(schemes))
	for i, s := range schemes {
		base := themeSlug(s.Name)
		seen[base]++
		if seen[base] == 1 {
			slugs[i] = base
			continue
		}
		slugs[i] = fmt.Sprintf("%s-%d", base, seen[base])
	}
	return slugs
}

func render(schemes []wtScheme) string {
	var b strings.Builder
	b.WriteString("// Code generated by go run gen_iterm_themes.go; DO NOT EDIT.\n")
	b.WriteString("// Source: mbadolato/iTerm2-Color-Schemes windowsterminal-themes.tgz\n")
	b.WriteString("// License: MIT, Copyright (c) 2011 to Present Mark Badolato.\n\n")
	b.WriteString("package styles\n\n")
	b.WriteString("var builtinItermThemes = map[string]terminalTheme{\n")
	slugs := uniqueSlugs(schemes)
	for i, s := range schemes {
		fmt.Fprintf(&b, "\t%q: {DisplayName: %q, Background: %q, Foreground: %q, Selection: %q, Black: %q, Red: %q, Green: %q, Yellow: %q, Blue: %q, Purple: %q, Cyan: %q, White: %q, BrightBlack: %q, BrightRed: %q, BrightGreen: %q, BrightYellow: %q, BrightBlue: %q, BrightPurple: %q, BrightCyan: %q, BrightWhite: %q},\n",
			slugs[i], s.Name, norm(s.Background), norm(s.Foreground), norm(s.SelectionBackground), norm(s.Black), norm(s.Red), norm(s.Green), norm(s.Yellow), norm(s.Blue), norm(s.Purple), norm(s.Cyan), norm(s.White), norm(s.BrightBlack), norm(s.BrightRed), norm(s.BrightGreen), norm(s.BrightYellow), norm(s.BrightBlue), norm(s.BrightPurple), norm(s.BrightCyan), norm(s.BrightWhite))
	}
	b.WriteString("}\n")
	return b.String()
}

var slugRE = regexp.MustCompile(`[^a-z0-9._-]+`)

func themeSlug(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	s = slugRE.ReplaceAllString(s, "-")
	s = strings.Trim(s, "-._")
	if s == "" {
		return "theme"
	}
	return s
}

func norm(s string) string {
	if s == "" {
		return "#000000"
	}
	return strings.ToUpper(s)
}
