package ui

import (
	"log/slog"
	"strings"

	"github.com/charmbracelet/glamour"

	"github.com/cfbender/hygge/internal/bus"
	"github.com/cfbender/hygge/internal/session"
	"github.com/cfbender/hygge/internal/ui/components"
)

func (a *App) refreshTodosCache() {
	a.todosCache = nil
	if a.opts.Store == nil {
		return
	}
	sid := a.rootSessionID()
	if sid == "" {
		return
	}
	items, _, err := a.opts.Store.GetSessionTodos(a.ctx, sid)
	if err != nil {
		slog.Warn("ui: refreshTodosCache: failed to load todos",
			"session_id", sid, "err", err)
		return
	}
	if len(items) == 0 {
		return
	}
	out := make([]components.SidebarTodo, 0, len(items))
	for _, it := range items {
		out = append(out, components.SidebarTodo{
			Title:  it.Content,
			Status: components.SidebarTodoStatus(it.Status),
		})
	}
	a.todosCache = out
}

// collapsedProjectPath returns opts.ProjectDir with the home directory
// prefix replaced by "~", mirroring the logic from the old HeaderBar.
func (a *App) collapsedProjectPath() string {
	p := a.opts.ProjectDir
	h := a.opts.HomeDir
	if h != "" && strings.HasPrefix(p, h) {
		rest := strings.TrimPrefix(p, h)
		if rest == "" {
			return "~"
		}
		return "~" + rest
	}
	return p
}

// sidebarSessionTitle returns the cached display title for the current root
// session.  The cache is populated synchronously in ensureSession, Init, and
// handleBusEvent (bus.MessageAppended) so this method never calls
// Store.GetSession on the render goroutine.
//
// Preference order: Slug → first 12 chars of session id.
func (a *App) sidebarSessionTitle() string {
	if a.sessionTitle != "" {
		return a.sessionTitle
	}
	// Fallback for the brief window before the cache is seeded (e.g.
	// immediately after Init before the first render with a known session).
	rootID := a.rootSessionID()
	if rootID == "" {
		return ""
	}
	if len(rootID) > 12 {
		return rootID[:12]
	}
	return rootID
}

// loadSessionTitle reads the session title from the store and returns the
// display string. Preference order: Slug → first 12 chars of session id. Used
// to populate a.sessionTitle synchronously on the Cmd goroutine so View() never
// blocks on store I/O. FirstMessagePreview is deliberately not used as a title;
// first-message titles must be generated by the title model and persisted as
// Slug before they are shown.
func (a *App) loadSessionTitle(id string) string {
	if id == "" {
		return ""
	}
	if a.opts.Store != nil {
		sess, err := a.opts.Store.GetSession(a.ctx, id)
		if err == nil && sess != nil {
			if sess.Slug != "" {
				return sess.Slug
			}
		}
	}
	// Fallback: first 12 chars of the session id.
	if len(id) > 12 {
		return id[:12]
	}
	return id
}

// appendThinkingDelta appends thinking text to the trailing streaming
// RoleAssistant message's Thinking field.  If the trailing message is not a
// streaming assistant, a new one is created with Thinking populated and Raw
// empty.  Thinking and text both live on one message; the message finalizes
// when the assistant turn completes.
func (a *App) appendThinkingDelta(text string) {
	if n := len(a.messages); n > 0 {
		last := &a.messages[n-1]
		if last.Role == components.RoleAssistant && last.IsStreaming {
			last.Thinking += text
			return
		}
	}
	a.messages = append(a.messages, uiMessage{
		Role:        components.RoleAssistant,
		Thinking:    text,
		Raw:         "",
		IsStreaming: true,
		AgentType:   a.ActiveModeName(),
		ModelName:   a.opts.ModelName,
		ModeColor:   a.activeModeColor(),
	})
}

// finalizeTrailingThinking is a no-op after Phase 2: thinking and text both
// live on the same RoleAssistant message, so there is nothing to "finalize"
// separately.  The function is preserved as a call-site placeholder so the
// existing handleBusEvent call graph compiles without changes in Phase 3.
func (a *App) finalizeTrailingThinking() {
	// Thinking lives inline on the assistant message — no separate row to
	// finalize.  This function is preserved as a call-site placeholder so the
	// existing handleBusEvent call graph compiles without changes.
}

// appendAssistantDelta appends text to the streaming assistant message, or
// starts a new one if the last message isn't a streaming assistant.
// Reuses the same streaming assistant uiMessage when thinking has already
// accumulated on it (thinking and text share one message in Phase 2).
func (a *App) appendAssistantDelta(text string) {
	if n := len(a.messages); n > 0 {
		last := &a.messages[n-1]
		if last.Role == components.RoleAssistant && last.IsStreaming {
			last.Raw += text
			last.FinalMarkdown = renderMarkdown(a.ensureRenderer(), last.Raw)
			return
		}
	}
	raw := text
	a.messages = append(a.messages, uiMessage{
		Role:          components.RoleAssistant,
		Raw:           raw,
		FinalMarkdown: renderMarkdown(a.ensureRenderer(), raw),
		IsStreaming:   true,
		AgentType:     a.ActiveModeName(),
		ModelName:     a.opts.ModelName,
		ModeColor:     a.activeModeColor(),
	})
}

// flushAssistantStream marks the current assistant message as final and renders
// it through glamour.  The messageID parameter is used to reconcile the live
// stream with the authoritative persisted message when available.
func (a *App) flushAssistantStream(role, messageID string) {
	if role != "assistant" {
		return
	}
	persisted, hasPersisted := a.persistedAssistantUIMessage(messageID)
	if hasPersisted {
		persisted.AgentType = a.ActiveModeName()
		persisted.ModelName = a.opts.ModelName
		persisted.ModeColor = a.activeModeColor()
		persisted.FinalMarkdown = renderMarkdown(a.ensureRenderer(), persisted.Raw)
	}
	idx := a.currentAssistantMessageIndex()
	if idx < 0 {
		if hasPersisted {
			a.insertPersistedAssistantMessage(persisted)
		}
		return
	}
	last := &a.messages[idx]
	last.IsStreaming = false
	last.Timestamp = a.opts.Now()
	if hasPersisted {
		last.Raw = persisted.Raw
		last.Thinking = persisted.Thinking
		last.Timestamp = persisted.Timestamp
		last.OutputTokens = persisted.OutputTokens
		last.CostUSD = persisted.CostUSD
		last.DurationMs = persisted.DurationMs
	}
	last.FinalMarkdown = renderMarkdown(a.ensureRenderer(), last.Raw)

	// Populate token/cost/duration from store if available.
	if !hasPersisted && a.opts.Store != nil && messageID != "" {
		if msg, err := a.opts.Store.GetMessage(a.ctx, messageID); err == nil && msg != nil {
			last.OutputTokens = msg.OutputTokens
			last.CostUSD = msg.CostUSD
			last.DurationMs = msg.DurationMs
			if !msg.CreatedAt.IsZero() {
				last.Timestamp = msg.CreatedAt
			}
		}
	}
}

func (a *App) currentAssistantMessageIndex() int {
	for i := len(a.messages) - 1; i >= 0; i-- {
		if a.messages[i].Role == components.RoleAssistant && a.messages[i].IsStreaming {
			return i
		}
	}
	if n := len(a.messages); n > 0 && a.messages[n-1].Role == components.RoleAssistant {
		return n - 1
	}
	return -1
}

func (a *App) insertPersistedAssistantMessage(msg uiMessage) {
	insertAt := len(a.messages)
	for insertAt > 0 && a.messages[insertAt-1].Role == components.RoleTool {
		insertAt--
	}
	a.messages = append(a.messages, uiMessage{})
	copy(a.messages[insertAt+1:], a.messages[insertAt:])
	a.messages[insertAt] = msg
}

func (a *App) persistedAssistantUIMessage(messageID string) (uiMessage, bool) {
	if a.opts.Store == nil || messageID == "" {
		return uiMessage{}, false
	}
	msg, err := a.opts.Store.GetMessage(a.ctx, messageID)
	if err != nil || msg == nil || msg.Role != session.RoleAssistant {
		return uiMessage{}, false
	}
	entries := uiEntriesFromStoreMessage(msg, map[string]session.Part{}, map[string]struct{}{})
	for _, entry := range entries {
		if entry.Role == components.RoleAssistant {
			return entry, true
		}
	}
	return uiMessage{}, false
}

// updateLastTool finds the most recent streaming tool entry with a matching
// name and finalises it with the result/error from the event.
func (a *App) updateLastTool(e bus.ToolCallCompleted) {
	for i := len(a.messages) - 1; i >= 0; i-- {
		msg := &a.messages[i]
		if msg.Role != components.RoleTool || !msg.IsStreaming {
			continue
		}
		if msg.ToolName != e.ToolName {
			continue
		}
		msg.IsStreaming = false
		if e.Err != "" {
			msg.IsError = true
			msg.Raw = e.Err
			msg.Status = components.ToolStatusError
		} else {
			msg.Status = components.ToolStatusCompleted
			msg.Raw = string(e.Result)
		}
		return
	}
	// No matching streaming tool entry — synthesise one.
	out := string(e.Result)
	status := components.ToolStatusCompleted
	if e.Err != "" {
		out = e.Err
		status = components.ToolStatusError
	}
	a.messages = append(a.messages, uiMessage{
		Role:     components.RoleTool,
		ToolName: e.ToolName,
		Raw:      out,
		IsError:  e.Err != "",
		Status:   status,
	})
}

// setToolStatus finds the most recent streaming RoleTool message with the
// given toolName and sets its Status field.  Used by the PermissionAsked
// handler to mark the row as awaiting permission.  No-op when no match
// is found (the tool row may not have arrived on the bus yet — rare race).
func (a *App) setToolStatus(toolName string, status components.ToolStatus) {
	for i := len(a.messages) - 1; i >= 0; i-- {
		msg := &a.messages[i]
		if msg.Role == components.RoleTool && msg.IsStreaming && msg.ToolName == toolName {
			msg.Status = status
			return
		}
	}
}

// setToolStatusByCurrentStatus finds the most recent RoleTool message whose
// Status equals fromStatus and transitions it to toStatus.  Used by the
// PermissionReplied handler to move the first awaiting-permission row to
// Running or Cancelled.  No-op when no match is found.
func (a *App) setToolStatusByCurrentStatus(fromStatus, toStatus components.ToolStatus) {
	for i := len(a.messages) - 1; i >= 0; i-- {
		msg := &a.messages[i]
		if msg.Role == components.RoleTool && msg.Status == fromStatus {
			msg.Status = toStatus
			return
		}
	}
}

// ensureRenderer constructs (or returns the cached) glamour renderer for the
// current bubble content width. msgColW is already the bubble content width
// (80% of the left column minus side bar + padding), so glamour word-wrap
// exactly matches the space available inside the bubble and content never
// overflows.
func (a *App) ensureRenderer() *glamour.TermRenderer {
	if a.renderer != nil && a.rendererW == a.msgColW {
		return a.renderer
	}
	w := a.msgColW
	if w <= 0 {
		w = 80
	}
	r, err := newRenderer(a.opts.Theme, w)
	if err != nil {
		return nil
	}
	a.renderer = r
	a.rendererW = w
	return a.renderer
}

func (a *App) rerenderFinalMarkdownMessages() {
	r := a.ensureRenderer()
	if r == nil {
		return
	}
	for i := range a.messages {
		msg := &a.messages[i]
		if msg.Raw == "" {
			continue
		}
		switch msg.Role {
		case components.RoleUser, components.RoleAssistant:
			msg.FinalMarkdown = renderMarkdown(r, msg.Raw)
		}
	}
	a.invalidateMsgCache()
}

// extractTarget makes a best-effort attempt to surface a useful target
// string (path, command) from a tool's raw JSON args.  Returns "" when the
// args don't decode or don't contain anything obvious.  We are intentionally
// duck-typed here — internal/ui must not depend on internal/tool schemas.
func extractTarget(args []byte) string {
	s := string(args)
	for _, key := range []string{`"path"`, `"file"`, `"command"`, `"url"`, `"target"`} {
		if _, after, ok := strings.Cut(s, key); ok {
			rest := after
			rest = strings.TrimLeft(rest, " \t:")
			if !strings.HasPrefix(rest, `"`) {
				continue
			}
			rest = rest[1:]
			before, _, ok := strings.Cut(rest, `"`)
			if !ok {
				continue
			}
			return before
		}
	}
	return ""
}

// extractPathFromArgs extracts the "filePath" or "path" field from a tool
// call's raw JSON args.  Used for write/edit tools to track modified files.
// Returns "" when the field is absent or the args cannot be decoded.
func extractPathFromArgs(args []byte) string {
	if len(args) == 0 {
		return ""
	}
	// Try both field names used by write/edit tools: "filePath" first
	// (write tool), then "path" (edit tool and some aliases).
	var fields struct {
		FilePath string `json:"filePath"`
		Path     string `json:"path"`
	}
	// Use the existing duck-typed extractor as a fast path before JSON decode.
	// Both "filePath" and "path" would be found by extractTarget("path"), but
	// we want the more specific JSON decode to avoid false positives from
	// values that contain the literal string "path".
	//
	// Note: encoding/json is not imported here because app.go already has it
	// through session/bus types.  We use a minimal inline parse via
	// extractTarget which is sufficient for this use case.
	if p := extractFieldString(args, "filePath"); p != "" {
		return p
	}
	if p := extractFieldString(args, "path"); p != "" {
		return p
	}
	_ = fields
	return ""
}

// extractFieldString extracts a top-level JSON string field by name from
// raw JSON bytes.  Returns "" when the field is absent or not a string.
// This is a lightweight alternative to a full json.Unmarshal when only one
// field is needed.
func extractFieldString(raw []byte, field string) string {
	key := `"` + field + `"`
	s := string(raw)
	_, after, ok := strings.Cut(s, key)
	if !ok {
		return ""
	}
	rest := after
	rest = strings.TrimLeft(rest, " \t\r\n:")
	if !strings.HasPrefix(rest, `"`) {
		return ""
	}
	rest = rest[1:]
	before, _, ok := strings.Cut(rest, `"`)
	if !ok {
		return ""
	}
	return before
}

// updateInputFocus sets input.Focused based on whether any modal is currently
// visible.  Call this after any change to activeModal or pendingPerms.
//
// Rule: the input border renders in the accent color only when no modal is
